default:
  find_CNV_upper: 1.175
  find_CNV_threshold: 0.1
  find_CNV_lower: -1.525
  
  # annotation track
  maxSize_anno: 20e6 # max size to show the transcripts
  maxtranscript: 30 # max number of transcript to show
  geneExtend: 1e5 # window size extend to 100kb
  
  # BAF plot track
  minseg: 50000 # min size to show allele specific Baf 50kb
  minsegmean: 1.02 # 0.47+0.55
  